site_name: AI/ML@DICE
theme: readthedocs
nav:
  - Home: 'index.md'
  - Write the Doc: 'projects/writingdocs.md'
  - Resources: 
    - 'projects/gpuserver.md'
  - Projects:
    - 'Sample Project': 'projects/sample_project.md'
